---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: jenkins
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-discovery
spec:
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 50000
    targetPort: 50000
    name: slaves
