apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: liatrio/kube-jenkins:latest
          env:
            - name: JOBLIST
              value: https://raw.githubusercontent.com/liatrio/liatrio-jenkins/kube/jenkins/jobs.json
            - name: JAVA_OPTS
              value: -Dhudson.Main.development=true -Djenkins.install.runSetupWizard=false -Dorg.apache.commons.jelly.tags.fmt.timeZone=America/Los_Angeles
            - name: KUBERNETES_NAMESPACE
              value: jenkins
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 30
            successThreshold: 2
            failureThreshold: 5
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-master-pvc
