# A Kubernetes ConfigMap providing the configuration-as-code for Jenkins
# Kubernetes Cloud Config w/ template
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-configuration-as-code
data:
  configuration-as-code.yaml: |
    unclassified:
      location:
        url: http://192.168.99.100:30000/
    jenkins:
      clouds:
        - kubernetes:
            name: kubernetes
            containerCapStr: 100
            jenkinsUrl: http://${MY_POD_IP}:8080
            templates:
              - name: jnlp-slave
                label: jnlp-slave
                nodeUsageMode: NORMAL
                containers:
                  - name: jnlp
                    image: jenkins/jnlp-slave:latest
                    alwaysPullImage: true
                    workingDir: "/home/jenkins"
                    ttyEnabled: true
                    command: /usr/local/bin/jenkins-slave
                    args: ""
                    resourceRequestCpu: "500m"
                    resourceLimitCpu: "1000m"
                    resourceRequestMemory: "1Gi"
                    resourceLimitMemory: "2Gi"
              - name: maven
                label: mavenpodtemplate
                nodeUsageMode: EXCLUSIVE
                containers:
                  - name: maven
                    image: maven:3.3.9-jdk-8-alpine
                    ttyEnabled: true
                    command: cat
                    args: ""
                    resourceRequestCpu: "500m"
                    resourceLimitCpu: "1000m"
                    resourceRequestMemory: "1Gi"
                    resourceLimitMemory: "2Gi"
                volumes:
                  - emptyDirVolume:
                      memory: false
                      mountPath: "/tmp"
                idleMinutes: "1"
                activeDeadlineSeconds: "120"
                slaveConnectTimeout: "1000"
