apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Value.teamName}}-jenkins-master-pvc
  labels:
    app: {{.Value.teamName}}-jenkins-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
