---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.teamName}}-jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: {{.Values.teamName}}-jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.teamName}}-jenkins-discovery
spec:
  type: NodePort
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins
