---
- copy:
    src: jenkins
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: u+rwx,g+rwx
- copy:
    src: Dockerfile
    dest: /home/ec2-user/Dockerfile
    owner: ec2-user
    group: ec2-user
    mode: u+rwx,g+rwx
- name: Build Jenkins image
  shell: docker build -t liatrio-jenkins .
- name: run Jenkins container
  shell: docker run -dp 8080:8080 liatrio-jenkins
