# A Kubernetes ConfigMap providing the configuration-as-code for Jenkins
# Kubernetes Cloud Config w/ template
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.teamName}}-jenkins-configuration-as-code
data:
  configuration-as-code.yaml: |
    unclassified:
      globalConfigFiles:
        configs:
        - mavenSettings:
            id: maven-settings
            name: maven-settings
            comment: maven-settings
            isReplaceAll: false
            serverCredentialMappings:
            - serverId: inhouse_snapshot
              credentialsId: snapshot
            - serverId: inhouse_release
              credentialsId: release
            content: |
              <settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                <profiles>
                  <profile>
                    <repositories>
                      <repository>
                        <snapshots>
                          <enabled>false</enabled>
                        </snapshots>
                        <id>central</id>
                        <name>libs-release</name>
                        <url>Artifactory URL</url>
                      </repository>
                      <repository>
                        <snapshots />
                        <id>snapshots</id>
                        <name>libs-snapshot</name>
                        <url>Artifactory URL</url>
                      </repository>
                    </repositories>
                    <pluginRepositories>
                      <pluginRepository>
                        <snapshots>
                          <enabled>false</enabled>
                        </snapshots>
                        <id>central</id>
                        <name>plugins-release</name>
                        <url>Artifactory URL</url>
                      </pluginRepository>
                      <pluginRepository>
                        <snapshots />
                        <id>snapshots</id>
                        <name>plugins-release</name>
                        <url>Artifactory URL</url>
                      </pluginRepository>
                    </pluginRepositories>
                    <id>artifactory</id>
                  </profile>
                </profiles>
                <activeProfiles>
                  <activeProfile>artifactory</activeProfile>
                </activeProfiles>
              </settings>
      location:
        url: http://${MY_POD_IP}:30000/
    jenkins:
      clouds:
        - kubernetes:
            name: kubernetes
            containerCapStr: 100
            jenkinsUrl: http://${MY_POD_IP}:8080
            templates:
              - name: docker
                label: docker
                nodeUsageMode: NORMAL
                containers:
                  - name: docker
                    image: "docker:1.11"
                    alwaysPullImage: true
                    workingDir: "/home/jenkins"
                    ttyEnabled: true
                    command: cat
                    args: ""
                    resourceRequestCpu: "500m"
                    resourceLimitCpu: "1000m"
                    resourceRequestMemory: "1Gi"
                    resourceLimitMemory: "2Gi"
                volumes:
                  - HostPathVolume:
                      hostPath: "/var/run/docker.sock"
                      mountPath: "/var/run/docker.sock"
              - name: jnlp-slave
                label: jnlp-slave
                nodeUsageMode: NORMAL
                containers:
                  - name: jnlp
                    image: jenkins/jnlp-slave:latest
                    alwaysPullImage: false
                    workingDir: "/home/jenkins"
                    ttyEnabled: true
                    command: /usr/local/bin/jenkins-slave
                    args: ""
                    resourceRequestCpu: "500m"
                    resourceLimitCpu: "1000m"
                    resourceRequestMemory: "1Gi"
                    resourceLimitMemory: "2Gi"
              - name: maven
                label: maven
                nodeUsageMode: EXCLUSIVE
                containers:
                  - name: maven
                    image: maven:3.3.9-jdk-8-alpine
                    ttyEnabled: true
                    command: cat
                    args: ""
                    resourceRequestCpu: "500m"
                    resourceLimitCpu: "1000m"
                    resourceRequestMemory: "1Gi"
                    resourceLimitMemory: "2Gi"
                volumes:
                  - emptyDirVolume:
                      memory: false
                      mountPath: "/tmp"
                idleMinutes: "1"
                activeDeadlineSeconds: "120"
                slaveConnectTimeout: "1000"
    jobs: {{.Values.jobs}}
    credentials: {{.Values.credentials}}
